<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="97338" started-at="2018-11-17T18:17:58Z" finished-at="2018-11-17T18:19:35Z">
    <groups>
    </groups>
    <test name="Test1" duration-ms="97338" started-at="2018-11-17T18:17:58Z" finished-at="2018-11-17T18:19:35Z">
      <class name="Academy.loginvalidationTest">
        <test-method status="PASS" signature="pagenavigation1(java.lang.String, java.lang.String)[pri:0, instance:Academy.loginvalidationTest@17cd7a0]" name="pagenavigation1" duration-ms="36926" started-at="2018-11-17T18:17:58Z" data-provider="getdata" finished-at="2018-11-17T18:18:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[monirul@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ibm]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pagenavigation1 -->
        <test-method status="PASS" signature="pagenavigation1(java.lang.String, java.lang.String)[pri:0, instance:Academy.loginvalidationTest@17cd7a0]" name="pagenavigation1" duration-ms="44872" started-at="2018-11-17T18:18:35Z" data-provider="getdata" finished-at="2018-11-17T18:19:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[test@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ibm]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pagenavigation1 -->
      </class> <!-- Academy.loginvalidationTest -->
      <class name="Academy.validationTest">
        <test-method status="FAIL" signature="validationTest()[pri:1, instance:Academy.validationTest@67ae56]" name="validationTest" duration-ms="15495" started-at="2018-11-17T18:19:20Z" finished-at="2018-11-17T18:19:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [FEATURED COURSES1] but found [FEATURED COURSES]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [FEATURED COURSES1] but found [FEATURED COURSES]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Academy.validationTest.validationTest(validationTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validationTest -->
      </class> <!-- Academy.validationTest -->
    </test> <!-- Test1 -->
  </suite> <!-- Suite -->
</testng-results>
